# Site
repository: codybullock.github.io
favicon: DSC_0077.jpg

# Content configuration version
version: 2

# Personal info
name: Cody Bullock
title: Hardware/Software Designer
email: codyb04@vt.edu
website: www.github.com/codybullock.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  codybullock
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: codybullock
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: profile_pic.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Cody and I'm a senior in Computer Engineering at Virginia Tech. In addition to my studies, I also participate in undergraduate research and plan to get my Master's in Computer Engineering.

  I am most skilled in: <mark>C++</mark> and <mark>Verilog HDL</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Home Audio System

        quote: >
          Designed and built a home audio system capable of altering the gain of certain frequency bands of an audio signal using potentiometers.
        description: | # this will include new lines to allow paragraphs
             This system was created using a Graphic Equalizer circuit and a Class-D Amplifier. LTspice was used for preliminary design and simulations and tested using an oscilloscope, wave generator, and network analyzer.
             
- title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: VT MICS Lab
        sub_title: Hardware/Software Designer
        caption: September 2024 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Currently working with the Virginia Tech Agriculture Department to develop a wireless sensor circuit that can measure pH, Lactate, and VFA, then send that data over LoRa. Working with a pH sensor prototype and designing a PCB with an MCU, three chemical sensors, and a LoRa module. Working with C++ for the embedded programming of the MCU, and giving weekly presentations on updates and progress.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Virignia Tech
        caption: 2022 - 2025
        sub_title: B.S. Computer Engineering
        #quote: >
          Studied abroad in Japan and South Korea
        description: | # this will include new lines to allow paragraphs
          Currently pursuing a B.S. in Computer Engineering. Along with being a current radio DJ for VT's student radio station, I was also a student mentor in my Sophomore year.

 # - title: A Little More About Me
 #   layout: text
 #   content: | # this will include new lines to allow paragraphs
 #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
 #     - Rock climbing
 #     - Gaming
 #     - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
